[package]
name = "rusty-modbus-codec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Modbus sans-IO encode/decode codec (no_std)"
readme = "README.md"

[dependencies]
rusty-modbus-types = { path = "../rusty-modbus-types", version = "0.1.1", default-features = false }

[features]
default = []
std = ["rusty-modbus-types/std"]

[package.metadata.docs.rs]
all-features = true
