#!/usr/bin/env python3
"""Validate the conformance ledger and check or generate its Markdown view."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from conformance_ledger import (
    LedgerError,
    check_generated_view,
    load_ledger,
    render_markdown,
    validate_ledger,
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="validate data and generated bytes")
    mode.add_argument("--write", action="store_true", help="validate data and write ledger.md")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    ledger_path = root / "docs/conformance/ledger.json"
    view_path = root / "docs/conformance/ledger.md"
    try:
        data = load_ledger(ledger_path)
    except LedgerError as error:
        print(error, file=sys.stderr)
        return 1

    errors = validate_ledger(data, root)
    if not errors and args.check:
        try:
            current = view_path.read_text(encoding="utf-8")
        except OSError as error:
            errors.append(f"cannot read {view_path}: {error}")
        else:
            errors.extend(check_generated_view(data, current))
    if errors:
        for error in errors:
            print(f"conformance ledger: {error}", file=sys.stderr)
        return 1

    if args.write:
        view_path.write_text(render_markdown(data), encoding="utf-8", newline="\n")
        print(f"wrote {view_path.relative_to(root)}")
    else:
        print(
            "conformance ledger valid: "
            f"{len(data['requirements'])} requirements, {len(data['tests'])} test files, "
            f"{len(data['profiles'])} profiles"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
